[package]
name = "mos6502"
version = "0.1.0"
authors = ["Rombertus"]
exclude = ["tests/**"]
edition = "2021"

[lib]
name = "mos6502"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
